/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package MyChat;

import java.rmi.RemoteException;
import java.util.logging.Level;
import java.util.logging.Logger;
import MyChat.Utilisateur.Contact;
import java.net.MalformedURLException;
import java.rmi.NotBoundException;

/**
 *
 * @author Jihad Nasser
 */
public class BroadCastForm extends javax.swing.JFrame {

    /**
     * Creates new form BroadCastForm
     */
    Utilisateur me;
    ClientGui cl;
    IServeur serverRef;
    
    public BroadCastForm(Utilisateur me, IServeur serverRef) {
        initComponents();
        this.me = me;
        this.serverRef = serverRef;
        for (Contact con : me.contacts.values()) {
            ContactesCombo.addItem(con.Id + " : " + con.nom);
        }
        ContactesCombo.setSelectedIndex(-1);
        MembresBroadCastTexta.setText("");
        MembresBroadCastTexta.append(me.Id + "\n");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        ContactesCombo = new javax.swing.JComboBox<>();
        BroadCastTextb = new javax.swing.JTextField();
        EnvoieBtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        MembresBroadCastTexta = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 51, 51));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 0, 255));
        jLabel1.setText("Les Membres Du Groupe");

        ContactesCombo.setFont(new java.awt.Font("sansserif", 2, 14)); // NOI18N
        ContactesCombo.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        ContactesCombo.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                ContactesComboItemStateChanged(evt);
            }
        });

        EnvoieBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MyChat/SendButton.jpg"))); // NOI18N
        EnvoieBtn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        EnvoieBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EnvoieBtnActionPerformed(evt);
            }
        });

        MembresBroadCastTexta.setEditable(false);
        MembresBroadCastTexta.setColumns(20);
        MembresBroadCastTexta.setRows(5);
        MembresBroadCastTexta.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jScrollPane1.setViewportView(MembresBroadCastTexta);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ContactesCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(BroadCastTextb, javax.swing.GroupLayout.PREFERRED_SIZE, 478, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(EnvoieBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(33, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(44, 44, 44)
                        .addComponent(ContactesCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(BroadCastTextb, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(EnvoieBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ContactesComboItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_ContactesComboItemStateChanged
        try {
            if (!MembresBroadCastTexta.getText().contains(ContactesCombo.getSelectedItem().toString().trim().split(":")[0].trim())) {
                MembresBroadCastTexta.append(ContactesCombo.getSelectedItem().toString().trim().split(":")[0].trim() + "\n");
            }
        } catch (Exception e) {

        }
    }//GEN-LAST:event_ContactesComboItemStateChanged

    private void EnvoieBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EnvoieBtnActionPerformed
        // TODO add your handling code here:
        String[] memberIds = MembresBroadCastTexta.getText().split("\n");
        String msg = BroadCastTextb.getText().trim();
        try {
            serverRef.EnvoieBroadCast(me.Id, memberIds, msg);
            MembresBroadCastTexta.append("Le message est envoye!!");
            BroadCastTextb.setText("");
        } catch (RemoteException ex) {
            Logger.getLogger(BroadCastForm.class.getName()).log(Level.SEVERE, null, ex);
        }
            this.dispose();
    }//GEN-LAST:event_EnvoieBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BroadCastForm(null, null).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JTextField BroadCastTextb;
    private javax.swing.JComboBox<String> ContactesCombo;
    private javax.swing.JButton EnvoieBtn;
    private javax.swing.JTextArea MembresBroadCastTexta;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
