/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package MyChat;

import java.rmi.RemoteException;
import java.util.logging.Level;
import java.util.logging.Logger;
import MyChat.Utilisateur.Contact;
import java.net.MalformedURLException;
import java.rmi.NotBoundException;
/**
 *
 * @author Jihad Nasser
 */
public class GroupeForm extends javax.swing.JFrame {

    /**
     * Creates new form GroupeForm
     */
    Utilisateur me;
    ClientImp clm;
    ClientGui cl;
    IServeur serverRef;

    public GroupeForm(Utilisateur me, IServeur serverRef) {
        initComponents();
        AjouterGroupBtn.setVisible(true);
        this.me = me;
        this.serverRef = serverRef;
        for (Contact con : me.contacts.values()) {
            ContactsCombo.addItem(con.Id + " : " + con.nom);
        }
        ContactsCombo.setSelectedIndex(-1);
        MembresGroupeTexta.setText("");
        MembresGroupeTexta.append(me.Id + "\n");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        ContactsCombo = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        AjouterGroupBtn = new javax.swing.JButton();
        NomDuGroupeTextb = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        MembresGroupeTexta = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 51, 51));

        ContactsCombo.setFont(new java.awt.Font("sansserif", 2, 14)); // NOI18N
        ContactsCombo.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        ContactsCombo.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                ContactsComboItemStateChanged(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 0, 255));
        jLabel1.setText("Les Membres Du Groupe");

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 204));
        jLabel2.setText("Nom Du Groupe");

        AjouterGroupBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MyChat/AjouterGroupeBtn.jpg"))); // NOI18N
        AjouterGroupBtn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        AjouterGroupBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AjouterGroupBtnActionPerformed(evt);
            }
        });

        NomDuGroupeTextb.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N

        MembresGroupeTexta.setEditable(false);
        MembresGroupeTexta.setColumns(20);
        MembresGroupeTexta.setRows(5);
        MembresGroupeTexta.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jScrollPane1.setViewportView(MembresGroupeTexta);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(NomDuGroupeTextb)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(ContactsCombo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 251, Short.MAX_VALUE))
                        .addGap(34, 34, 34)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(AjouterGroupBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(39, 39, 39))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(NomDuGroupeTextb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 100, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(ContactsCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1))
                .addGap(36, 36, 36)
                .addComponent(AjouterGroupBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(53, 53, 53))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AjouterGroupBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AjouterGroupBtnActionPerformed
        // TODO add your handling code here:
        String[] memberIds = MembresGroupeTexta.getText().split("\n");
        String groupName = NomDuGroupeTextb.getText().trim();
        try {
            serverRef.AddGroupe(groupName, memberIds);
        } catch (RemoteException ex) {
            Logger.getLogger(GroupeForm.class.getName()).log(Level.SEVERE, null, ex);
        }
        try {
            cl = new ClientGui(me.Id);
        } catch (NotBoundException ex) {
            Logger.getLogger(GroupeForm.class.getName()).log(Level.SEVERE, null, ex);
        } catch (MalformedURLException ex) {
            Logger.getLogger(GroupeForm.class.getName()).log(Level.SEVERE, null, ex);
        }
            this.dispose();
    }//GEN-LAST:event_AjouterGroupBtnActionPerformed

    private void ContactsComboItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_ContactsComboItemStateChanged
        try {
            if (!MembresGroupeTexta.getText().contains(ContactsCombo.getSelectedItem().toString().trim().split(":")[0].trim())) {
                MembresGroupeTexta.append(ContactsCombo.getSelectedItem().toString().trim().split(":")[0].trim() + "\n");
            }
        } catch (Exception e) {

        }
    }//GEN-LAST:event_ContactsComboItemStateChanged
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GroupeForm(null, null).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AjouterGroupBtn;
    private javax.swing.JComboBox<String> ContactsCombo;
    private javax.swing.JTextArea MembresGroupeTexta;
    public javax.swing.JTextField NomDuGroupeTextb;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
